// This file is autogenerated. Changes will be overwritten.
#include "2LCCYRVYXB/moc_cameraview.cpp"
#include "2LCCYRVYXB/moc_customvideowidget.cpp"
#include "2LCCYRVYXB/moc_customvideowidgetsurface.cpp"
#include "2LCCYRVYXB/moc_userhelpdialog.cpp"
